services:

  backend-dev:
    build:
      context: ..
      dockerfile: .devcontainer/backend/Dockerfile
    image: aidevops-backend-dev
    command: sleep infinity
  
    ports:
      - "8080:8080"

    working_dir: /workspaces/SoftwareAi/backend
    volumes:
      - ..:/workspaces/SoftwareAi:cached
      - maven-cache:/home/vscode/.m2
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:postgresql://postgres:5432/aidevops_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      JWT_SECRET: 1234567890123456789012345678901234567890

      AI_BASE_URL: http://ollama:11434
      AI_GENERATE_PATH: /api/chat
      AI_MODEL: llama3.2

      GITLAB_URL: https://gitlab.com
      GITLAB_TOKEN: ""
      GITLAB_WEBHOOK_TOKEN: change-me

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - aidevops-network

  frontend-dev:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-20-bookworm
    command: sleep infinity
    working_dir: /workspaces/SoftwareAi/frontend
    volumes:
      - ..:/workspaces/SoftwareAi:cached
      - npm-cache:/home/node/.npm

    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"

    depends_on:
      - backend-dev

    networks:
      - aidevops-network

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aidevops_dev

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d aidevops_dev"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - aidevops-network

  pgadmin:
    image: dpage/pgadmin4:8
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "5050:80"

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - aidevops-network

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"

    volumes:
      - ollama-data:/root/.ollama

    networks:
      - aidevops-network
networks:
  aidevops-network:
    driver: bridge

volumes:
  postgres-data:
  maven-cache:
  npm-cache:
  ollama-data: